version: "3.8"
name: food-assistant

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.35.9
    ports:
      - 8002:8000
      - 50051:50051
    volumes:
      - ../data/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"

  embedder:
    build: ../modules/embedder
    ports:
      - 8001:8000
    restart: on-failure:0
